\c my_bookshop

CREATE TABLE IF NOT EXISTS users (
  user_id SERIAL PRIMARY KEY
);

-- ALTER TABLE reviews
-- ADD COLUMN user_id INT REFERENCES users(user_id) ON DELETE CASCADE;

INSERT INTO users DEFAULT VALUES; 
INSERT INTO users DEFAULT VALUES;
INSERT INTO users DEFAULT VALUES;
INSERT INTO users DEFAULT VALUES;
INSERT INTO users DEFAULT VALUES;
INSERT INTO users DEFAULT VALUES;
INSERT INTO users DEFAULT VALUES;
INSERT INTO users DEFAULT VALUES;
INSERT INTO users DEFAULT VALUES;
INSERT INTO users DEFAULT VALUES;
